version: 2

# Build documentation in the docs/ directory with Sphinx
sphinx:
  builder: html
  configuration: docs/conf.py
  fail_on_warning: true

# Declare the Python requirements required to build your docs
build:
  os: ubuntu-22.04
  tools:
    python: "3.10"
    nodejs: "latest"
  commands:
    - pip install -r docs/req.txt
    - npm install -g typedoc