name: markdown-autodocs

on:
    branches:    
      - '**'        # matches every branch
    workflow-dispatch:

jobs:        
  auto-update-readme:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v4
        - name: Markdown autodocs
          uses: dineshsonachalam/markdown-autodocs@v1.0.2