name: Changelog
on:
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate Changelog
        id: changelog
        uses: ardalanamini/auto-changelog@v4
        with:
          github-token: ${{ secrets.token }}
          commit-types: |
            feat    : New Features
            fix     : Bug Fixes
            build   : Build System & Dependencies
            perf    : Performance Improvements
            docs    : Documentation
            test    : Tests
            refactor: Refactors
            chore   : Chores
            ci      : CI
            style   : Code Style
            revert  : Reverts
          default-commit-type: Other Changes
          release-name: v1.1.0
          release-name-prefix: ""
          mention-authors: true
          mention-new-contributors: true
          include-compare-link: true
          include-pr-links: true
          include-commit-links: true
          semver: true
          use-github-autolink: true