name: Generate Changelog

on:
  push:
    branches:
      - master
  workflow_dispatch:

permissions:
  contents: write

jobs:
  changelog:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install conventional-changelog-conventionalcommits

      - name: Generate Changelog
        uses: TriPSs/conventional-changelog-action@v5
        with:
          github-token: ${{ secrets.TOKEN }}
          git-message: 'docs(changelog): update changelog'
          output-file: "CHANGELOG.md"
          skip-on-empty: false
          skip-version-file: true
          create-summary: true
          skip-bump: true
          skip-tag: true

      - name: Install Pandoc
        run: sudo apt-get install -y pandoc

      - name: Convert Markdown to ReStructuredText
        run: pandoc CHANGELOG.md -o history.rst

      - name: Commit and Push Changelog
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add CHANGELOG.md history.rst
          git commit -m "docs(changelog): update changelog"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}