name: Close Issue Automatically

on:
  schedule:
    - cron: "0 */3 * * *"  # Setiap 3 jam

permissions:
  issues: write

jobs:
  close_old_issues:
    runs-on: ubuntu-latest
    steps:
      - name: Close Stale Issues
        uses: peter-evans/close-issue@v3
        with:
          issue-title: "❌ Workflow Failure - "
          comment: "✅ Masalah telah diperiksa dan issue ini ditutup secara otomatis."
          close-reason: "completed"
          days-before-close: 0