name: CI
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20.9.0' # Ganti versi sesuai dengan kebutuhan proyek Anda

    - name: Install modules
      run: yarn install # Bisa diganti dengan npm install jika Anda menggunakan npm

    - name: Run ESLint
      run: npx eslint . -c .js,.jsx,.ts,.tsx