name: Open Issue on Failure

on:
  workflow_run:
    workflows: ["Lint & Auto-Fix JavaScript"]
    types:
      - completed

permissions:
  issues: write

jobs:
  open_issue:
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    runs-on: ubuntu-latest
    steps:
      - name: Create Issue
        uses: dacbd/create-issue-action@main
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          title: |
            [${{ github.event.workflow_run.name }}] failed during [${{ github.event_name }}]

          assignees: ${{ github.actor }}
          labels: Skill-Issue, Failure
          body: |
            ## Failure Report:
            
            > [!IMPORTANT]
            > Details on failed run: [View Run](https://github.com/${{ github.repository }}/actions/runs/${{ github.event.workflow_run.id }})
    
            - **Author**: @${{ github.event.workflow_run.actor }}
            - **Branch**: `${{ github.event.workflow_run.head_branch }}`
            - **Commit**: ${{ github.event.workflow_run.head_sha }}
    
            - [ ] **Task**: Bad Code Detected, fix the issue(s), and re-run until successful.
    
            > This issue was created automatically by GitHub, 
            > **DO NOT** close this issue until resolved.