name: generator docs
on:
  push:
    branches:
      - master

jobs:
  thedocs:
    runs-on: ubuntu-latest

    steps:
    - name: Build
      uses: andstor/jsdoc-action@v1
      with:
        recurse: true