name: Deploy JSDoc to GitHub Pages

on:
  push:
    branches:
      - master  # Ganti dengan `main` jika pakai `main`

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Install JSDoc & Dependencies
        run: npm install --save-dev jsdoc clean-jsdoc-theme

      - name: Create output directory
        run: mkdir -p jsdocs

      - name: Generate JSDoc
        run: npx jsdoc -c jsdoc.json

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: jsdocs
          clean: true