name: Release

on:
  workflow_dispatch:
    branches:
      - master

jobs:
  latest-tag:
    name: Run latest-tag
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

  publish-npm:
    name: Publish on NPM
    runs-on: ubuntu-latest
    permissions:
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Node.js (without cache)
        uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: "https://registry.npmjs.org"

      - name: Install pnpm
        uses: pnpm/action-setup@v3
        with:
          version: latest

      - name: Ensure pnpm-lock.yaml exists
        run: |
          if [ ! -f pnpm-lock.yaml ]; then
            echo "pnpm-lock.yaml not found, generating..."
            pnpm install --lockfile-only
          else
            echo "pnpm-lock.yaml already exists."
          fi

      - name: Install Node.js (with cache)
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "pnpm"
          registry-url: "https://registry.npmjs.org"

      - name: Install dependencies
        run: pnpm install --ignore-scripts --frozen-lockfile

      - name: Get package version
        id: package_version
        run: echo "VERSION=$(node -p 'require("./package.json").version')" >> $GITHUB_ENV

      - name: Publish package to NPM
        run: |
          pnpm publish --access public --no-git-checks
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM }}
          NPM_CONFIG_PROVENANCE: true

      - name: Deprecate previous version
        run: |
          PREV_VERSION=$(npm show @er-npm/scraper versions --json | jq -r 'sort | reverse | .[1]')
          if [ -n "$PREV_VERSION" ]; then
            echo "Checking if previous version ($PREV_VERSION) is already deprecated..."
            DEPRECATED=$(npm show @er-npm/scraper@$PREV_VERSION deprecated --json | jq -r '.')
          if [ "$DEPRECATED" == "null" ] || [ -z "$DEPRECATED" ]; then
            echo "Deprecating previous version: $PREV_VERSION"
            pnpm deprecate "@er-npm/scraper@$PREV_VERSION" "Versi ini telah usang, silakan perbarui ke versi terbaru."
          else
            echo "Previous version $PREV_VERSION is already deprecated. Skipping."
            fi
          else
            echo "No previous version found or only one version exists, skipping deprecation."
          fi
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM }}