name: Release

on:
  workflow_dispatch:  # Hanya berjalan secara manual

jobs:
  publish-npm:
    name: Publish on NPM
    runs-on: ubuntu-latest
    permissions:
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Node.js & pnpm
        uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: "https://registry.npmjs.org"
          cache: "pnpm"

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Ensure pnpm-lock.yaml exists
        run: |
          if [ ! -f pnpm-lock.yaml ]; then
            echo "pnpm-lock.yaml not found, generating..."
            pnpm install --lockfile-only
          fi

      - name: Install dependencies
        run: pnpm install --ignore-scripts --frozen-lockfile

      - name: Get package version
        id: package_version
        run: echo "VERSION=$(node -p 'require("./package.json").version')" >> $GITHUB_ENV

      - name: Publish package to NPM
        run: pnpm publish --access public --no-git-checks
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM }}
          NPM_CONFIG_PROVENANCE: true

      - name: Install jq (JSON Processor)
        run: sudo apt-get install -y jq

      - name: Deprecate previous version (if exists)
        run: |
          PREV_VERSION=$(npm show @er-npm/scraper versions --json | jq -r 'sort | reverse | .[1]')
          if [ -n "$PREV_VERSION" ]; then
            echo "Checking if previous version ($PREV_VERSION) is already deprecated..."
            DEPRECATED=$(npm show @er-npm/scraper@$PREV_VERSION deprecated --json | jq -r '.')
            if [ "$DEPRECATED" == "null" ] || [ -z "$DEPRECATED" ]; then
              echo "Deprecating previous version: $PREV_VERSION"
              pnpm deprecate "@er-npm/scraper@$PREV_VERSION" "Versi ini telah usang, silakan perbarui ke versi terbaru."
            else
              echo "Previous version $PREV_VERSION is already deprecated. Skipping."
            fi
          else
            echo "No previous version found or only one version exists, skipping deprecation."
          fi
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM }}
        continue-on-error: true