on:
  workflow_dispatch: # Bisa dijalankan manual lewat GitHub Actions
  push:
    branches:
      - master
    paths:
      - "package.json"

name: Auto Bump Version

permissions:
  contents: write

jobs:
  bumpVersion:
    name: Bump Package Version
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Bump Version
        run: |
          NEW_VERSION=$(npm version patch --no-git-tag-version)
          echo "New version: $NEW_VERSION"

      - name: Commit and Push Changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add package.json
          git commit -m "chore: bump version to $(jq -r .version package.json) [skip ci]" || exit 0
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}